### ISSUE TITLE
How to get the previous version using deb-s3?

### ISSUE THREAD

**Issue by shanukus98765** [krobertson/deb-s3#112]
deb-s3 generates Packages.gz while doing `deb-s3 upload`.

Suppose I am using s3 as my custom apt-repository with the package: `alpha-pkg`

Now, when I do `sudo apt-get update`, then only the latest version of alpha-pkg comes. All the previous versions are gone. Is there any way to keep the previous versions too?

This way, I can quickly switch back to any previous version of `alpha-pkg`

**Comment by shanukus98765** [comment]
Hi, Any updates on this?

**Comment by krobertson** [comment]
You can do this with the `--preserve-versions` on the `deb-s3 upload` command. I'd also suggest looking through the help screens with either `deb-s3 upload --help` for some of the different arguments.

Then the previous versions listed in the manifest will be preserved. To add the old ones back, you will have to re-upload them, but uploading the file itself will be skipped since it already exists.

To install a previous version, you have to specify the version to use with `apt-get install alpha-pkg=1.2.3`. I don't know if interfaces like `aptitude` will list all of them or not, I don't generally use them.
