### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by cbarraford** [krobertson/deb-s3#14]
Be nice is deb-s3 had a config file with the default bucket name, aws keys, etc.

**Comment by rcoup** [comment]
It already supports the [AWS credentials](http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs) environment variables & ~/.aws/credentials files via [aws-sdk](https://github.com/aws/aws-sdk-ruby).

Would be nice to support `AWS_REGION` automatically instead of needing `--endpoint` though.
