### ISSUE TITLE
Avoid overwriting old versions

### ISSUE THREAD

**Issue by tfheen** [krobertson/deb-s3#46]
It would be useful if you needed to pass --force-overwrite (or similar) to overwrite existing versions of packages.

(Alternatively, have a --no-overwrite if you disagree about the default.)

**Comment by whiteley** [comment]
The package is overwritten but so are the manifests and the repository is left in a valid state. As long as the user has run `apt-get update` since the upload, the install will succeed without issue. I think the default behavior should be to not upload existing packages whether they have changed or not, both to save on transfers and to allow `deb-s3 upload *.deb` behavior.

@krobertson would you be fine with the `--force-overwrite` option as described? If so, I'm happy to put it together. Also, great package - thanks! :+1:

**Comment by BrianAdams** [comment]
Jus to add, if when overwriting, the system should check all of the other places that might have links to that same package and the manifest for those need to be refreshed with the new package. This is because a package with the same file name may have a different hash value (perhaps because it was signed at a different time) and the overwrite will break the other manifests if they are not updated.
