### ISSUE TITLE
Install these packages without verification [y/N]

### ISSUE THREAD

**Issue by mslinn** [krobertson/deb-s3#92]
I created a PPA with deb-s3, and it worked very well. However, when users try to install the package hosted in the PPA, they are asked if they want to install without verification. How can I get rid of this message?

<pre>
$ <b>sudo add-apt-repository 'deb http://mslinn-ppa.s3.amazonaws.com stable main'</b>
$ <b>sudo apt-get update</b>
$ <b>sudo apt-get install pound</b>
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  pound
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 105 kB of archives.
After this operation, 239 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  pound
Install these packages without verification? [y/N] <b>y</b>
E: Some packages could not be authenticated
</pre>

**Comment by kedare** [comment]
You have to sign your packages

http://blog.jonliv.es/blog/2011/04/26/creating-your-own-signed-apt-repository-and-debian-packages/

**Comment by mslinn** [comment]
Thanks, I will check it out

**Comment by mslinn** [comment]
The article discusses signing the repo as well as the packages, and references files that don't exist in repos made with `deb-s3`. Is it necessary or even possible to sign repos made with `deb-s3`? How much of the cited article is relevant, and if those instructions are followed will other warnings appear?

**Comment by krobertson** [comment]
@mslinn Sorry I hadn't seen this issue when it was first filed!

The article @kedare links to is close to what you'd want. It isn't generally necessary to sign packages, or packages and the repository. I typically just sign the repository. The repository manifest contains the URLs to all the packages, the checksums, as well as the size. This effectively validates all the packages referenced in one, since the host will validate the checksums when downloading.

To have the package repository be signed, simply add the `--sign` argument when running `deb-s3 upload`. This will upload the package, add it to the repository manifest, and then sign the manifest. If you have a specific key you want to sign with, then use `--sign=KEYID` and it will use that specific key.

Then as the article mentions, you can use `apt-key` on the individual machines to add your key to the local trusted keyring.

**Comment by mslinn** [comment]
I have uploaded a few unsigned packages. I don't have updates yet. How do set things right?

**Comment by krobertson** [comment]
If you do `deb-s3 verify --sign` it should force an update with it signed.

**Comment by mslinn** [comment]
It would be helpful to add more detail to `README.md` about the `verify --sign` command / option combination. Currently it just says:

````
Usage:
  deb-s3 verify

Options:
  -f, [--fix-manifests]                 # Whether to fix problems in manifests when verifying.
      [--sign=SIGN]                     # Sign the Release file. Use --sign with your key ID to use a specific key.
````

**Comment by mslinn** [comment]
Please don't close this issue. I would very much like to run `deb-s3 verify --sign` but I still don't know how!

**Comment by krobertson** [comment]
I am not going to extend the dialog to document how to use GPG, especially since Googling it is so easy and will yield vastly superior docs.

From the looks of your output, it seems your `gpg --gen-key` might have failed. Especially from the last paragraph.  There are some good [GPG cheat sheets](http://irtfweb.ifa.hawaii.edu/~lockhart/gpg/) out there to show some useful commands. 

GPG key IDs are a string that is generated to identify your key. Believe it is a SHA1. If you do a `gpg --list-keys`, it will show the short version of the key ID. You'll likely see `rsa2048/XYZ`, where `XYZ` is the shortened version of the key ID.

**Comment by mslinn** [comment]
For posterity, this is what I did:
````
$ gpg --list-keys
/home/mslinn/.gnupg/pubring.gpg
-------------------------------
pub   2048R/AB12CD34 2015-12-19
uid                  Michael Slinn <mslinn@micronauticsresearch.com>
sub   2048R/9D4B4321 2015-12-19

$ deb-s3 verify --sign AB12CD34 --bucket mslinn-ppa
>> Retrieving existing manifests
>> Checking for missing packages in: stable/main amd64
>> Removing 0 package(s) from the manifest...
   -- Transferring dists/stable/main/binary-amd64/Packages
   -- Transferring dists/stable/main/binary-amd64/Packages.gz
   -- Transferring dists/stable/Release
/var/lib/gems/2.1.0/gems/deb-s3-0.7.1/lib/deb/s3/release.rb:106: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
   -- Transferring dists/stable/Release.gpg
>> Update complete.
>> Checking for missing packages in: stable/main i386
>> Removing 0 package(s) from the manifest...
   -- Transferring dists/stable/main/binary-i386/Packages
   -- Transferring dists/stable/main/binary-i386/Packages.gz
   -- Transferring dists/stable/Release
   -- Transferring dists/stable/Release.gpg
>> Update complete.
````
